### PR TITLE
added calendar url

### PR DESCRIPTION
**Pull request by Draco9421**

### CODE REVIEW

**Comment by ashishsonamm** [comment]
Your API fetches an output like this - 
 `[
    "/images/admission2020/New ACAD CAL for First Year.pdf",
    "/Downloads/student/2020-21 CALEANDER - Higher Sem.pdf"
]`
I need the titles too. Something like this 
`[
   {
       title: "first title", link: "link 1"
    },
    {
       title: "second title", link: "link 2"
    }
]`

**Comment by Draco9421** [comment]
> Your API fetches an output like this -
> `[ "/images/admission2020/New ACAD CAL for First Year.pdf", "/Downloads/student/2020-21 CALEANDER - Higher Sem.pdf" ]`
> I need the titles too. Something like this
> `[ { title: "first title", link: "link 1" }, { title: "second title", link: "link 2" } ]`

but why do you need them we will upload only one calendar.

**Comment by ashishsonam** [comment]
> > Your API fetches an output like this -
> > `[ "/images/admission2020/New ACAD CAL for First Year.pdf", "/Downloads/student/2020-21 CALEANDER - Higher Sem.pdf" ]`
> > I need the titles too. Something like this
> > `[ { title: "first title", link: "link 1" }, { title: "second title", link: "link 2" } ]`
> 
> but why do you need them we will upload only one calendar.

**Comment by Draco9421** [comment]
isko herkou pe update kar dena
kyoki credentials tere pass he.

**Comment by ashishsonamm** [comment]
> isko herkou pe update kar dena
> kyoki credentials tere pass he.

noted.

**Pull request merged**
